# Generated by Django 5.1.7 on 2025-04-03 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subastas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="stock",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
