# Generated by Django 5.1.7 on 2025-04-03 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subastas", "0002_alter_auction_price_alter_auction_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
